### ISSUE TITLE
Home Assistant 0.107 deprecating 'Groups' causing errors in lmscontrols.yaml

### ISSUE THREAD

**Issue by mapex007** [ynot123/LMS_Controls#25]
Hello,

I recently upgraded to Home assistant 0.107.1 and after the reboot i received an alert that the configs in my installation that referenced groups was deprecated and would need to be removed. 

Below are the lines that were causing the error:
```
# LMS GUI Master Sync Controls 
  - alias: "LMS GUI Master Sync Command OFF"
    initial_state: true
    trigger:
    - platform: state
      entity_id: input_select.lms_sync_master
    action:
    - service: input_boolean.turn_off
      data_template:
        entity_id: group.lms_sync_players

group:
  lms_controls:
    name: LMS Controls
    view: yes
    entities:
        - group.lms_player
        - group.lms_sync_players
        - group.all_lms_players
```
Below is the related documentation from the HA 0.107 release:

Groups - Groups are NOT being removed, but the configuration options, services, and service options related to the (previously deprecated and now removed) States UI are now removed in this release. This includes:

The view and control configuration options for a group.
The group.set_visibility service call
The control, visible, view options on the group.set service call
Please ensure your configuration and automations do not use these anymore. - (@frenck - #32021) (group docs)

I use the LMS controls quite a lot and love the integration so i rolled back the upgrade to 0.106.6 in which the configuration runs perfectly. 

Any assistance is greatly appreciated. 

Many Thanks!
