### ISSUE TITLE
lmscontrols

### ISSUE THREAD

**Issue by lafontaj** [ynot123/LMS_Controls#32]
Hi, i'm new to HA but i'm using LMS since long time.  I love what you did and il wish to put that in place at home.

I'm not really familiar with HA but i know Linux, terminal, web server etc...

I have install HA on a pi and i did put in place the reverse proxy to be able to reach my HA from internet with SSL enable on my webserver.

I did copy everything on HA and customize what it need to be.  When validating the config file after the edition of lmscontrols, there is errors about the group part.
```
group:
  lms_controls:
    name: LMS Controls
    view: yes
    entities:
        - group.lms_player
        - group.lms_sync_players
        - group.all_lms_players


  lms_player:
    name: LMS Music Player Controls
    control: hidden
    entities:
    - input_select.lms_player
    - input_number.lms_volume
    - input_number.lms_sleep_time
    - input_select.lms_source
    - input_text.lms_artist
    - input_text.lms_album
    - input_text.lms_song
    - input_text.lms_playlist
    - input_select.lms_command
    - script.lms_cmd_pause_player
    - script.lms_cmd_start_player
    - script.lms_cmd_next_track
    - input_boolean.lms_shuffle
    - input_boolean.lms_repeat
```

It look like the "view" and "control" are not possible any more for "group".  So i put comment on those lines to achieved a config verification.

Its end up with a non functioning installation. i'm not able to reach the players.  Maybe my error is somewhere else but since i modified something, i just want to be sure. 

Thanks,

Jean

**Comment by lafontaj** [comment]
Hi,
I finally start everything again, its working overall, but still problem with the group property that block the verification of HA.

I'm waiting for my Alpha right now.

I'll learn more about HA in the next days, but if you have some informations about that, it will be great.

Thanks

**Comment by olni** [comment]
..i have the same issue, would be nice if someone could explain what went wrong here.
I use HA 2021.12.3

> 

![lms_error](https://user-images.githubusercontent.com/10218872/147386512-0f43a5c7-cf31-439a-91e1-4f18cf11b191.png)

**Comment by lafontaj** [comment]
Hi,
I don't know if your are stuck there.  Just comment the line (by adding #) 

```
group:
  lms_controls:
    name: LMS Controls
#    view: yes
    entities:
        - group.lms_player
        - group.lms_sync_players
        - group.all_lms_players


  lms_player:
    name: LMS Music Player Controls
#    control: hidden
    entities:
    - input_select.lms_player
    - input_number.lms_volume
    - input_number.lms_sleep_time
    - input_select.lms_source
    - input_text.lms_artist
    - input_text.lms_album
    - input_text.lms_song
    - input_text.lms_playlist
    - input_select.lms_command
    - script.lms_cmd_pause_player
    - script.lms_cmd_start_player
    - script.lms_cmd_next_track
    - input_boolean.lms_shuffle
    - input_boolean.lms_repeat

  lms_sync_players:
    name: List of Sync Players
    entities:
###  To be updated as required
###       add or remove comments to enable upto 10 players
    - input_select.lms_sync_master
    - input_boolean.lms_player1_sync
    - input_boolean.lms_player2_sync
    - input_boolean.lms_player3_sync
    - input_boolean.lms_player4_sync
    - input_boolean.lms_player5_sync
    - input_boolean.lms_player6_sync
#    - input_boolean.lms_player7_sync
#    - input_boolean.lms_player8_sync
#    - input_boolean.lms_player9_sync
#    - input_boolean.lms_player10_sync
#    - type: divider
    - input_text.lms_qry_result

  all_lms_players:
    name: All LMS Media Players
    icon: mdi:music
#    control: hidden
#    view: no
###  To be updated as required
###       Update the media_player entities below to view player status in GUI
    entities:
#      - media_player.googlehome
#      - media_player.googlemini_1
      - media_player.pixel
      - media_player.mediaroom
      - media_player.kitchen
      - media_player.desktop
      - media_player.host
      - media_player.masterbedroom
```

You will be able to continue to the next step.
I thinks that those line only affect the presentation of the dashboard.  I did not run in to problem by doing this.  I'm far from being a specialist.  Eventually i'll understand those lines.

Bye!
